apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shoot-csi-driver-controller
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: shoot
spec:
  selector:
    matchLabels:
      app: csi
      role: controller
  endpoints:
    - port: metrics
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
      metricRelabelings:
        - sourceLabels:
            - __name__
          action: keep
          regex: ^(csidriver_operation_errors)$
