apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: csi-snapshot-webhook-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: gcp-csi-snapshot-validation
      minAllowed:
        memory: {{ .Values.csiSnapshotValidationWebhook.resources.requests.memory }}  
        cpu: {{ .Values.csiSnapshotValidationWebhook.resources.requests.cpu }}  
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csi-snapshot-validation
  updatePolicy:
    updateMode: Auto
