---
apiVersion: v1
kind: Secret
metadata:
  name: dnsrecord-external
  namespace: shoot--foobar--gcp
type: Opaque
data:
# serviceaccount.json: base64(serviceaccount-json)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--gcp
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      networking:
        pods: 10.243.128.0/17
        services: 10.243.0.0/17
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: DNSRecord
metadata:
  name: dnsrecord-external
  namespace: shoot--foobar--gcp
spec:
  type: google-clouddns
  secretRef:
    name: dnsrecord-external
    namespace: shoot--foobar--gcp
# zone: dnstest/example.com
  name: api.gcp.foobar.shoot.example.com
  recordType: A # Use A, CNAME, or TXT
  values: # list of IP addresses for A records, a single hostname for CNAME records, or a list of texts for TXT records.
  - 1.2.3.4
# ttl: 120
