---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--gcp
type: Opaque
data:
  serviceaccount.json: ZGF0YQo=
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--gcp
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1beta1
    kind: CloudProfile
    spec:
      providerConfig:
        apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
        kind: CloudProfileConfig
        machineImages:
        - name: coreos
          versions:
          - version: 2135.6.0
            image: gcpimageid
  seed:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Shoot
    spec:
      kubernetes:
        version: 1.28.2
    status:
      lastOperation:
        state: Succeeded
---
# This resource does result in the deployment of the machine-controller-manager, the machine classes,
# and the desired MachineDeployments. However, it does not create actual virtual machines because the
# provided infrastructure status data (subnet name, etc.) is not valid/does not exist.
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: worker
  namespace: shoot--foobar--gcp
  annotations:
    gardener.cloud/operation: reconcile
spec:
  type: gcp
  region: europe-west1
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--gcp
  infrastructureProviderStatus:
    apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    serviceAccountEmail: foo@bar.com
    networks:
      subnets:
      - purpose: nodes
        name: nodes-subnet
  pools:
  - name: cpu-worker
    machineType: n1-standard-4
    machineImage:
      name: coreos
      version: 2135.6.0
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
  # labels:
  #   key: value
  # annotations:
  #   key: value
  # taints: # See also https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  # - key: foo
  #   value: bar
  #   effect: NoSchedule
    userData: IyEvYmluL2Jhc2gKCmVjaG8gImhlbGxvIHdvcmxkIgo=
    volume:
      type: pd-standard
      size: 20Gi
  # dataVolumes:
  #   - name: alpha
  #   - type: SCRATCH
  # providerConfig: # GCP provider specific config
  #   apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
  #   kind: WorkerConfig
  #   volume: # provider specific volume configuration
  #     interface: "SCSI" # applies only for scratch disks, the local SSD Interface.
  #     encryption: # Encryption Details
  #       kmsKeyName: "projects/projectId/locations/<zoneName>/keyRings/<keyRingName>/cryptoKeys/alpha"
  #       kmsKeyServiceAccount: "user@projectId.iam.gserviceaccount.com"
  #   gpu:
  #     acceleratorType: nvidia-tesla-t4
  #     count: 1
  #   serviceAccount:
  #     email: foo@bar.com
  #     scopes:
  #     - https://www.googleapis.com/auth/cloud-platform
  #   nodeTemplate:
  #     capacity:
  #       cpu: 2
  #       gpu: 1
  #       memory: 50Gi
    zones:
    - europe-west1-b
