apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gardener-extension-admission-gcp
webhooks:
- name: mutation.gcp.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  # Please make sure you are running `gardener@v1.42` or later before enabling this object selector.
  objectSelector:
    matchLabels:
      provider.extensions.gardener.cloud/gcp: "true"
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://localhost:9443/webhooks/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrakNDQWVLZ0F3SUJBZ0lRWVlvRklZU2UyQjdMZEk1ODdnNHJDVEFOQmdrcWhraUc5dzBCQVFzRkFEQVgKTVJVd0V3WURWUVFERXd4bllYSmtaVzVsY2kxa1pYWXdIaGNOTWpFd01USXhNVEF6TVRFd1doY05NekV3TVRJeApNVEF6TVRFd1dqQVhNUlV3RXdZRFZRUURFd3huWVhKa1pXNWxjaTFrWlhZd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDLy9IcEZEN3Z4clRmREp3Y3JMNW0zdUtVajVvMWw0NEtGRHFxQWg2L1AKblJQUlN3ZHR5M2YvYkQ1TVRXOUplOWsvajYrWHZwUmc3LzFLbmRkaGpObDdGUjVSejdacDF0TkVEZkJqd2pLVwpJeGRHYnRCaUcwZ1c0aDZ1aEFwcTk5aDk1NWtMQkhTVW1XUFRRZFNtQ0lEY1lnSmd6OGZXdFRQTmxVSUtaajVCCkUxSGsrazgxZjhnTGZsaXpuRkNFeUNHNHRuWm1XbXpVUXljdXdoQnpFSCt5N1QyZEgwN0VBM3V3SmFwZG5WTGMKSlhsVEUzQm1QY3RXNCs3dGM4eUNKd3BuUjlMdE51MTVtaUtWNVNKaHlTaTUzdmo5MUlFQXVOa0wrMDZMbmlOSAp4RVVnRlljUlZPOTZPcjZGSW9EYlFvZGlQbU1OWDJHaHd6bzhpMFFvNHNFakFnTUJBQUdqUWpCQU1BNEdBMVVkCkR3RUIvd1FFQXdJQnBqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCUUJxTWdPKzJ1RG1KWHIKdUJwQ3lqaW9NbDZMTFRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWZRZXZldzFLOXJaWStwNmlmVGhXWm9SWQo5Y3RldzdTdjlCak4vdzZrazRML1V2ZHdML0NZWkZJUWR0Tm5uSjcrMXdxT093L1NEdi9HZ2ZTUlVhTlZkbEVFCmx1S003VGhTbGl1SFVJTS9IblpLdUFxQVpFUU5LQ0RDSnFDYkplS1BGYnJKcFZqMU1Xblc2YzV5L3dTMHJxOUsKRXludVJTQnMvOVEvOVg1NVBaZjRFZnhQN29UVGY4L2pIRnJ0ODdBT2ZqUGUzYlMxV1FGdHh3NVZyWm13TC9CbgpTNXlEcUpPTDNsR0xUeG9vOGhHNS9ucDZ0NkFXOXVoM2FxQ3FsZ051MmEwUndJSTBicmVFb3NZZmhlL0NXbkxBCmxhcVNKc0kydHBjeW4zMEFQbzlpRU9JVjYwc2VET3p6VGxyMm5oa2NURFBYZ2drWktCWWFncGlrTUZobGRBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
