machineClasses:
- name: class-1
# resourceLabels:
#   foo: bar
  region: europe-west1
  zone: europe-west1-b
  canIpForward: true
  deletionProtection: false
  description: An optional description for machines created by that class.
  disks:
  - autoDelete: true
    boot: true
    sizeGb: 20
    type: pd-standard
    image: projects/coreos-cloud/global/images/coreos-stable-1576-5-0-v20180105
    labels:
      name: my-disk
#   CMEK Encryption
#   encryption:
#     kmsKeyName: projects/projId/locations/zone/keyRings/keyRingName/cryptoKeys/keyName
#     kmsKeyServiceAccount: name@projId.iam.gserviceaccount.com

#  local SSD
#  - autoDelete: true
#    boot: false
#    type: SCRATCH
#    interface: <localSSDInterface>
#    image: projects/coreos-cloud/global/images/coreos-stable-1576-5-0-v20180105
#    labels:
#      name: my-disk
# gpu:
#   acceleratorType: nvidia-tesla-t4
#   count: 1
  labels:
    name: mcm
  metadata:
    - key: "block-project-ssh-keys"
      value: "TRUE"
  machineType: n1-standard-4
  nodeTemplate:
    architecture: amd64
    capacity:
      cpu: 2
      gpu: 1
      memory: 25Gi
    instanceType: n1-standard-4
    region: europe-west1
    zone: europe-west1-b
  networkInterfaces:
  - subnetwork: my-subnet
    disableExternalIP: true
    # can be IPV4_ONLY or IPV4_IPV6
    stackType: IPV4_ONLY
    ipv6accessType: EXTERNAL
    ipCidrRange: "/24"
    subnetworkRangeName: "ipv4-pod-cidr"
  scheduling:
    automaticRestart: true
    onHostMaintenance: MIGRATE
    preemptible: false
  secret:
    cloudConfig: abc
  credentialsSecretRef:
    name: cloudprovider
    namespace: shoot-namespace
  serviceAccounts:
  - email: serviceaccount@my-project.iam.gserviceaccount.com
    scopes:
    - https://www.googleapis.com/auth/compute
  tags:
  - my-nodes
