images:
  machine-controller-manager: image-repository:image-tag
  machine-controller-manager-provider-gcp: image-repository:image-tag

replicas: 1

podAnnotations: {}

podLabels: {}

providerName: provider-foo

# injected by generic worker actuator
genericTokenKubeconfigSecretName: generic-token-kubeconfig

namespace:
  uid: uuid-of-namespace

metricsPort: 10258
metricsPortGCP: 10259

vpa:
  enabled: true
  updatePolicy:
    updateMode: "Auto"
