apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- name: cluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster

- name: cloudProfile
  schema:
    type: object
    properties:
      # it is assumed that the disable_machine_images have already been removed
      machineImages:
        type: array

# data from landscape-*-setup/export/kubernetes/KUBERNETES_VERSIONS.yaml
# versions of item with name 'aws'
- name: kubernetesVersions
  schema:
    type: array

# data from landscape-*-setup/landscape.yaml section gardener-extension-provider-aws.values
- name: controllerRegistration
  schema:
    type: object
    properties:
      concurrentSyncs:
        type: integer
      resources:
        type: object
        properties:
          requests:
            type: object
            properties:
              cpu:
                type: string
              memory:
                type: string
          limits:
            type: object
            properties:
              cpu:
                type: string
              memory:
                type: string
      vpa:
        scheme:
          type: object

- name: imageVectorOverwrite
  schema:
    type: object
    properties:
      images:
        type: array
        items:
          type: object

exports: []

exportExecutions: []

subinstallations: []

deployExecutions:
- file: /deploy-execution-manifests.yaml
  name: manifests
  type: GoTemplate
