---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    {{- if eq .Values.defaultStorageClass "default" }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-sc-hdd
  annotations:
    {{- if eq .Values.defaultStorageClass "gce-sc-hdd" }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-sc-fast
  annotations:
    {{- if eq .Values.defaultStorageClass "gce-sc-fast" }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
volumeBindingMode: WaitForFirstConsumer

{{- if .Values.hyperdisk.balanced }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-sc-hd-balanced
  annotations:
    {{- if eq .Values.defaultStorageClass "gce-sc-hd-balanced" }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
  {{- if .Values.hyperdisk.balanced.provisionedIopsOnCreate }}
  provisioned-iops-on-create: {{ .Values.hyperdisk.balanced.provisionedIopsOnCreate | quote }}
  {{- end }}
  {{- if .Values.hyperdisk.balanced.provisionedThroughputOnCreate }}
  provisioned-throughput-on-create: {{ .Values.hyperdisk.balanced.provisionedThroughputOnCreate | quote }}
  {{- end }}
volumeBindingMode: WaitForFirstConsumer
{{- end }}

{{- if .Values.hyperdisk.throughput }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-sc-hd-throughput
  annotations:
    {{- if eq .Values.defaultStorageClass "gce-sc-hd-throughput" }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-throughput
  {{- if .Values.hyperdisk.throughput.provisionedThroughputOnCreate }}
  provisioned-throughput-on-create: {{ .Values.hyperdisk.throughput.provisionedThroughputOnCreate | quote }}
  {{- end }}
volumeBindingMode: WaitForFirstConsumer
{{- end }}

{{- if .Values.hyperdisk.extreme }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-sc-hd-extreme
  annotations:
    {{- if eq .Values.defaultStorageClass "gce-sc-hd-extreme" }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-extreme
  {{- if .Values.hyperdisk.extreme.provisionedIopsOnCreate }}
  provisioned-iops-on-create: {{ .Values.hyperdisk.extreme.provisionedIopsOnCreate | quote }}
  {{- end }}
volumeBindingMode: WaitForFirstConsumer
{{- end }}

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  annotations:
    {{- if .Values.managedDefaultVolumeSnapshotClass }}
    snapshot.storage.kubernetes.io/is-default-class: "true"
    {{- end }}
  name: default
driver: pd.csi.storage.gke.io
deletionPolicy: Delete

{{- if .Values.filestore.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-filestore
provisioner: filestore.csi.storage.gke.io
parameters:
  # Name of the VPC. Note that non-default VPCs require special firewall rules to be setup
  network: {{ .Values.filestore.network }}
  # standard (default) or premier or enterprise
  tier: standard
allowVolumeExpansion: true
{{- end }}
