{{- if .Values.useLegacyProvisioner }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard

---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: gce-sc-fast
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-ssd
{{- end }}
