apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: tm-extension-gcp-
  namespace: default
spec:
  ttlSecondsAfterFinished: 172800 # 2 days
  {{- if .Values.revision }}
  locationSets:
  - default: true
    name: provider-gcp
    locations:
    - type: git
      repo: https://github.com/gardener/gardener-extension-provider-gcp.git
      revision: {{ .Values.revision }}
  {{- end }}

  config:
  - name: SERVICEACCOUNT_JSON
    type: env
    valueFrom:
      secretKeyRef:
        name: shoot-operator-gcp
        key: serviceaccount.json

  testflow:
  - name: infrastructure-test
    definition:
      name: infrastructure-test
      config:
        - name: REGION
          type: env
          value: europe-west1
        - name: RECONCILER
          type: env
          value: tf
  - name: infra-flow-test
    definition:
      name: infrastructure-test
      config:
        - name: REGION
          type: env
          value: europe-west1
        - name: RECONCILER
          type: env
          value: flow
  - name: infra-migrate-test
    definition:
      name: infrastructure-test
      config:
      - name: REGION
        type: env
        value: europe-west1
      - name: RECONCILER
        type: env
        value: migrate
  - name: bastion-test
    definition:
      name: bastion-test
      config:
      - name: REGION
        type: env
        value: europe-west1