{
 "title": "CSI Driver Controller",
 "tags": [
  "controlplane",
  "seed",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{type=~\"seed\", pod=~\"csi-driver-controller.+\"}, container)"
   },
   { "name": "severity", "label": "Severity", "query": "INFO,WARN,ERR,DBG,NOTICE,FATAL" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Shows the CPU usage and shows the requests and limits.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"csi-driver-controller-(.+)\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"csi-driver-controller-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"csi-driver-controller-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"csi-driver-controller-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"csi-driver-controller-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"csi-driver-controller-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{pod_name=~\"csi-driver-controller-(.+)\", container_name=~\"$container\", severity=~\"$severity\"} |~ \"$search\""
    }
   ]
  }
 ]
}