name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}
      version-commit-callback-action-path: .github/actions/prepare-release
    permissions:
      contents: read

  oci-images:
    name: Build OCI-Images
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    uses: gardener/cc-utils/.github/workflows/oci-ocm.yaml@master
    strategy:
      matrix:
        args:
          - name: gardener-extension-provider-gcp
            target: gardener-extension-provider-gcp
            oci-repository: gardener/extensions/provider-gcp
            ocm-labels:
              name: gardener.cloud/cve-categorisation
              value:
                network_exposure: protected
                authentication_enforced: false
                user_interaction: gardener-operator
                confidentiality_requirement: high
                integrity_requirement: high
                availability_requirement: high
          - name: gardener-extension-admission-gcp
            target: gardener-extension-provider-gcp
            oci-repository: gardener/extensions/admission-gcp
            ocm-labels:
              name: gardener.cloud/cve-categorisation
              value:
                network_exposure: protected
                authentication_enforced: false
                user_interaction: end-user
                confidentiality_requirement: high
                integrity_requirement: high
                availability_requirement: high
    with:
      name: ${{ matrix.args.name }}
      version: ${{ needs.prepare.outputs.version }}
      target: ${{ matrix.args.target }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: ${{ matrix.args.oci-repository }}
      oci-platforms: linux/amd64,linux/arm64
      ocm-labels: ${{ toJSON(matrix.args.ocm-labels) }}
      extra-tags: latest

  helmcharts:
    name: Build Helmcharts
    needs:
      - prepare
      - oci-images
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: gardener/cc-utils/.github/workflows/helmchart-ocm.yaml@master
    strategy:
      matrix:
        args:
          - name: provider-gcp
            dir: charts/gardener-extension-provider-gcp
            oci-repository: charts/gardener/extensions
            ocm-mappings:
              - ref: ocm-resource:gardener-extension-provider-gcp.repository
                attribute: image.repository
              - ref: ocm-resource:gardener-extension-provider-gcp.tag
                attribute: image.tag
          - name: admission-gcp-application
            dir: charts/gardener-extension-admission-gcp/charts/application
            oci-repository: charts/gardener/extensions
            ocm-mappings:
              - ref: ocm-resource:gardener-extension-admission-gcp.repository
                attribute: image.repository
              - ref: ocm-resource:gardener-extension-admission-gcp.tag
                attribute: image.tag
          - name: admission-gcp-runtime
            dir: charts/gardener-extension-admission-gcp/charts/runtime
            oci-repository: charts/gardener/extensions
            ocm-mappings:
              - ref: ocm-resource:gardener-extension-admission-gcp.repository
                attribute: image.repository
              - ref: ocm-resource:gardener-extension-admission-gcp.tag
                attribute: image.tag
    with:
      name: ${{ matrix.args.name }}
      dir: ${{ matrix.args.dir }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: ${{ matrix.args.oci-repository }}
      ocm-mappings: ${{ toJSON(matrix.args.ocm-mappings) }}

  sast-lint:
    uses: gardener/cc-utils/.github/workflows/sastlint-ocm.yaml@master
    permissions:
      contents: read
    with:
      linter: gosec
      run: make sast-report
