name: Build
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - labeled
  merge_group:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: snapshot
    secrets: inherit
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write

  component-descriptor:
    uses: gardener/cc-utils/.github/workflows/post-build.yaml@master
    needs:
      - build
    secrets: inherit
    permissions:
      id-token: write
      contents: write
