name: Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        type: choice
        options:
          - noop
          - finalize
        description: 'Select whether to modify the release version.'
      next-version:
        type: choice
        options:
          - bump-minor
          - bump-patch
        description: 'Select the type of version bump for the next release.'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: write
      id-token: write
      packages: write
    with:
      mode: release
      release-version: ${{ inputs.release-version }}

  release-to-github-and-bump:
    uses: gardener/cc-utils/.github/workflows/release.yaml@master
    needs:
      - build
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      packages: write
    with:
      release-commit-target: branch
      next-version: ${{ inputs.next-version }}
      next-version-callback-action-path: .github/actions/prepare-release
      slack-channel-id: C9CEBQPGE # #sap-tech-gardener
